(()=>{'use strict';
const cfg=window.TELEFABRYKA_CONFIG||{},configured=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY),db=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null,$=id=>document.getElementById(id);
const STATUSES=['Przyjęte','Diagnoza','Oczekiwanie na część','W naprawie','Gotowe','Wydane','Anulowane'];
const BRAND_ICONS={apple:'apple',samsung:'samsung',xiaomi:'xiaomi',huawei:'huawei',honor:'honor',motorola:'motorola',oppo:'oppo',realme:'realme',oneplus:'oneplus',google:'google',nothing:'nothing',nokia:'nokia'};
let items=[],orders=[],staff=[],deviceModels=[],serviceTemplates=[],session=null,profile=null,currentOrder=null,signatureDirty=false,printAfterSave=false,smartChosen=[],adminPricePage=1,adminPriceQuery='',adminPriceFilter='all';
const ADMIN_PRICE_PAGE_SIZE=100;
const esc=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>Number(v||0).toLocaleString('pl-PL',{minimumFractionDigits:0,maximumFractionDigits:2})+' zł',fmt=d=>d?new Date(d).toLocaleString('pl-PL'):'—',dateOnly=d=>d?new Date(d).toLocaleDateString('pl-PL'):'—',initials=s=>(s||'?').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const priceText=i=>`${i.price_prefix?i.price_prefix+' ':''}${money(i.price)}`;function roleName(r){return({admin:'Administrator',employee:'Pracownik',technician:'Serwisant'})[r]||r}
function brandKey(name=''){const n=name.toLowerCase();return Object.keys(BRAND_ICONS).find(k=>n.includes(k))||''}function iconUrl(name){const k=brandKey(name);return k?`https://cdn.simpleicons.org/${BRAND_ICONS[k]}/111827`:''}
function toast(t,type='warn'){const e=$('statusBanner');e.textContent=t;e.className='status'+(type==='error'?' error':'');setTimeout(()=>e.classList.add('hidden'),4500)}
function download(name,text,mime='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:mime}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n')}
async function loadItems(){const {data,error}=await db.from('price_items').select('*').order('brand').order('model');if(error)return toast(error.message,'error');items=data||[];renderPrices()}
function renderPrices(){const q=$('searchInput').value.trim().toLowerCase(),oldB=$('brandFilter').value,oldC=$('categoryFilter').value,visible=items.filter(i=>i.is_visible!==false),brands=[...new Set(visible.map(i=>i.brand))].sort((a,b)=>a.localeCompare(b,'pl')),cats=[...new Set(visible.map(i=>i.category||'Inne'))].sort((a,b)=>a.localeCompare(b,'pl'));$('brandFilter').innerHTML='<option value="">Wszystkie marki</option>'+brands.map(x=>`<option>${esc(x)}</option>`).join('');$('categoryFilter').innerHTML='<option value="">Wszystkie kategorie</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('');if(brands.includes(oldB))$('brandFilter').value=oldB;if(cats.includes(oldC))$('categoryFilter').value=oldC;$('brandStrip').innerHTML=brands.map(x=>`<button class="brand-chip" data-brand-chip="${esc(x)}">${iconUrl(x)?`<img src="${iconUrl(x)}" alt="">`:''}${esc(x)}</button>`).join('');const b=$('brandFilter').value,c=$('categoryFilter').value,filtered=visible.filter(i=>(!b||i.brand===b)&&(!c||(i.category||'Inne')===c)&&(!q||`${i.brand} ${i.model} ${i.category||''} ${i.service} ${i.description||''}`.toLowerCase().includes(q)));$('priceList').innerHTML='';filtered.forEach(i=>{const n=$('cardTemplate').content.cloneNode(true),img=n.querySelector('.brand-mark img'),url=iconUrl(i.brand);if(url)img.src=url;else{img.remove();n.querySelector('.brand-mark').textContent=initials(i.brand)}n.querySelector('.tag').textContent=i.category||i.brand;n.querySelector('h2').textContent=`${i.brand} ${i.model}`;n.querySelector('.service').textContent=i.service;n.querySelector('.description').textContent=i.description||'Cena orientacyjna';n.querySelector('.price').textContent=priceText(i);$('priceList').appendChild(n)});$('emptyState').classList.toggle('hidden',filtered.length>0)}
async function refreshAuth(){const {data}=await db.auth.getSession();session=data.session;profile=null;if(session){const {data:p}=await db.from('staff_profiles').select('*').eq('user_id',session.user.id).maybeSingle();profile=p;if(!profile?.active){await db.auth.signOut();session=null;profile=null;toast('Konto jest nieaktywne.','error')}}$('adminButton').textContent=session?'Otwórz panel':'Panel pracownika'}
async function openPanel(){await refreshAuth();if(!session){$('loginError').textContent='';$('loginDialog').showModal();return}await loadPanel();$('adminDialog').showModal()}
async function loadPanel(){const admin=profile?.role==='admin';document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden-role',!admin));$('adminName').textContent=profile?.display_name||'';$('adminEmail').textContent=profile?.username||session.user.email;$('adminRole').textContent=roleName(profile?.role);await Promise.all([loadItems(),loadOrders(),admin?loadStaff():Promise.resolve(),admin?loadCatalog():Promise.resolve()]);renderAdminPrices();renderOrders();renderDashboard();renderStaff();renderProfile();renderPeriodStats()}
async function loadOrders(){const {data,error}=await db.from('service_orders').select('*, accepted_by_profile:staff_profiles!service_orders_accepted_by_fkey(display_name,username), updated_by_profile:staff_profiles!service_orders_updated_by_fkey(display_name)').order('created_at',{ascending:false});if(error){orders=[];toast('Błąd zleceń: '+error.message,'error')}else orders=data||[]}
async function loadStaff(){const {data,error}=await db.from('staff_profiles').select('*').order('display_name');staff=error?[]:(data||[])}
function ensureAdminPriceControls(){
 const rows=$('adminRows');if(!rows)return;const wrap=rows.closest('.table-wrap');if(!wrap)return;
 wrap.style.maxHeight='58vh';wrap.style.overflowY='auto';wrap.style.overflowX='auto';
 if(!$('adminPriceControls')){
  const box=document.createElement('div');box.id='adminPriceControls';box.className='admin-price-controls';
  box.innerHTML=`<input id="adminPriceSearch" class="admin-price-search" type="search" placeholder="Szukaj marki, modelu lub usługi…"><select id="adminPriceFilter"><option value="all">Wszystkie</option><option value="visible">Aktywne</option><option value="hidden">Ukryte</option><option value="zero">Bez ceny</option></select><span id="adminPriceCount"></span>`;
  wrap.parentNode.insertBefore(box,wrap);
  $('adminPriceSearch').value=adminPriceQuery;$('adminPriceFilter').value=adminPriceFilter;
  $('adminPriceSearch').oninput=e=>{adminPriceQuery=e.target.value;adminPricePage=1;renderAdminPrices()};
  $('adminPriceFilter').onchange=e=>{adminPriceFilter=e.target.value;adminPricePage=1;renderAdminPrices()};
 }
 if(!$('adminPricePager')){
  const pager=document.createElement('div');pager.id='adminPricePager';pager.className='admin-price-pager';wrap.insertAdjacentElement('afterend',pager);
 }
 if(!$('adminPricePatchStyle')){
  const st=document.createElement('style');st.id='adminPricePatchStyle';st.textContent=`.admin-price-controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:12px 0}.admin-price-search{flex:1;min-width:230px;padding:11px 13px;border-radius:10px;border:1px solid rgba(255,255,255,.2);background:rgba(8,25,45,.75);color:#fff}.admin-price-controls select{padding:11px 13px;border-radius:10px;background:#102b49;color:#fff;border:1px solid rgba(255,255,255,.2)}.admin-price-pager{display:flex;justify-content:center;align-items:center;gap:12px;margin:14px 0}.status-toggle{border:0;border-radius:999px;padding:7px 11px;font-weight:800;cursor:pointer}.status-toggle.visible{background:#34d399;color:#052e24}.status-toggle.hidden-status{background:#f59e0b;color:#2d1600}.table-wrap thead th{position:sticky;top:0;z-index:2;background:#173b61}`;document.head.appendChild(st);
 }
}
function filteredAdminPrices(){const q=adminPriceQuery.trim().toLowerCase();return items.filter(i=>{const text=`${i.brand} ${i.model} ${i.category||''} ${i.service} ${i.description||''}`.toLowerCase();if(q&&!text.includes(q))return false;if(adminPriceFilter==='visible'&&!i.is_visible)return false;if(adminPriceFilter==='hidden'&&i.is_visible)return false;if(adminPriceFilter==='zero'&&Number(i.price||0)>0)return false;return true})}
function renderAdminPrices(){ensureAdminPriceControls();const list=filteredAdminPrices(),pages=Math.max(1,Math.ceil(list.length/ADMIN_PRICE_PAGE_SIZE));adminPricePage=Math.min(Math.max(1,adminPricePage),pages);const start=(adminPricePage-1)*ADMIN_PRICE_PAGE_SIZE,shown=list.slice(start,start+ADMIN_PRICE_PAGE_SIZE);$('adminRows').innerHTML=shown.map(i=>`<tr><td><strong>${esc(i.brand)}</strong><small>${esc(i.model)}</small></td><td>${esc(i.category||'Inne')}<small>${esc(i.service)}</small></td><td>${esc(priceText(i))}</td><td><button type="button" class="status-toggle ${i.is_visible?'visible':'hidden-status'}" data-toggle-visible="${i.id}">${i.is_visible?'Aktywna':'Ukryta'}</button></td><td>${profile?.role==='admin'?`<div class="row-actions"><button class="button button-small" data-edit="${i.id}">Edytuj</button><button class="button button-small button-danger" data-delete="${i.id}">Usuń</button></div>`:'—'}</td></tr>`).join('')||'<tr><td colspan="5">Brak pozycji spełniających filtry.</td></tr>';
 if($('adminPriceCount'))$('adminPriceCount').textContent=`${list.length} pozycji · ${start+1}-${Math.min(start+shown.length,list.length)}`;
 if($('adminPricePager'))$('adminPricePager').innerHTML=`<button class="button button-small" data-price-page="prev" ${adminPricePage<=1?'disabled':''}>← Poprzednia</button><strong>Strona ${adminPricePage} z ${pages}</strong><button class="button button-small" data-price-page="next" ${adminPricePage>=pages?'disabled':''}>Następna →</button>`;
}
function filteredOrders(){const q=$('orderSearch').value.trim().toLowerCase(),s=$('orderStatusFilter').value,p=$('orderPriorityFilter').value;return orders.filter(o=>(!s||o.status===s)&&(!p||o.priority===p)&&(!q||`${o.order_number} ${o.customer_name} ${o.customer_phone} ${o.device_brand} ${o.device_model} ${o.imei||''}`.toLowerCase().includes(q)))}
function renderOrders(){$('orderRows').innerHTML=filteredOrders().map(o=>`<tr><td><strong>${esc(o.order_number)}</strong><small>${fmt(o.created_at)}</small></td><td>${esc(o.customer_name)}<small>${esc(o.customer_phone)}</small></td><td>${esc(o.device_brand)} ${esc(o.device_model)}<small>${esc(o.fault_description)}</small></td><td><select class="status-select" data-status-id="${o.id}">${STATUSES.map(x=>`<option ${x===o.status?'selected':''}>${x}</option>`).join('')}</select></td><td><span class="priority ${esc(o.priority||'Standard')}">${esc(o.priority||'Standard')}</span></td><td class="amount">${money(o.final_amount||o.estimated_amount)}</td><td>${esc(o.accepted_by_profile?.display_name||'—')}</td><td><div class="row-actions"><button class="button button-small" data-order-edit="${o.id}">Edytuj</button><button class="button button-small" data-print="${o.id}">Drukuj</button><button class="button button-small" data-history="${o.id}">Historia</button>${profile?.role==='admin'?`<button class="button button-small button-danger" data-order-delete="${o.id}">Usuń</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="8">Brak zleceń.</td></tr>'}
function renderDashboard(){const active=orders.filter(o=>o.status!=='Anulowane'),today=new Date().toISOString().slice(0,10),todayOrders=active.filter(o=>String(o.created_at).slice(0,10)===today),issuedToday=active.filter(o=>o.status==='Wydane'&&String(o.updated_at).slice(0,10)===today),todayRevenue=issuedToday.reduce((a,o)=>a+Number(o.final_amount||0),0),cards=[['Przyjęte dziś',todayOrders.length],['W naprawie',active.filter(o=>o.status==='W naprawie').length],['Gotowe',active.filter(o=>o.status==='Gotowe').length],['Obrót dziś',money(todayRevenue)]];$('statsCards').innerHTML=cards.map(x=>`<article class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');$('todayLabel').textContent=new Date().toLocaleDateString('pl-PL');const max=Math.max(1,...STATUSES.map(s=>orders.filter(o=>o.status===s).length));$('statusStats').innerHTML=STATUSES.map(s=>{const n=orders.filter(o=>o.status===s).length;return `<div class="progress-row"><span>${s}</span><div class="progress"><i style="width:${n/max*100}%"></i></div><strong>${n}</strong></div>`}).join('');$('recentOrders').innerHTML=orders.slice(0,7).map(o=>`<div class="recent-item"><div><strong>${esc(o.order_number)} · ${esc(o.device_brand)} ${esc(o.device_model)}</strong><small>${esc(o.customer_name)} · ${fmt(o.created_at)}</small></div><span class="pill">${esc(o.status)}</span></div>`).join('')||'<p class="description">Brak zleceń.</p>';const map={};orders.forEach(o=>{const n=o.accepted_by_profile?.display_name||'Nieznany';map[n]??={count:0,issued:0,value:0};map[n].count++;if(o.status==='Wydane'){map[n].issued++;map[n].value+=Number(o.final_amount||0)}});$('employeeStats').innerHTML=Object.entries(map).sort((a,b)=>b[1].count-a[1].count).map(([n,v])=>`<div class="employee-row"><strong>${esc(n)}</strong><span>${v.count} przyjętych / ${v.issued} wydanych</span><span class="amount">${money(v.value)}</span></div>`).join('')||'<p class="description">Brak danych.</p>'}
function renderStaff(){if(profile?.role!=='admin')return;const q=($('staffSearch')?.value||'').toLowerCase();$('staffCards').innerHTML=staff.filter(s=>`${s.display_name} ${s.username} ${s.role}`.toLowerCase().includes(q)).map(s=>{const own=s.user_id===session.user.id;return `<article class="staff-card"><div class="staff-head"><div class="avatar">${initials(s.display_name)}</div><div><h3>${esc(s.display_name)}</h3><p>@${esc(s.username||'—')} · ${esc(roleName(s.role))}</p></div></div><p>${s.active?'Konto aktywne':'Konto zablokowane'} · od ${dateOnly(s.created_at)}</p><div class="staff-actions"><button class="button button-small" data-staff-edit="${s.user_id}">Edytuj</button><button class="button button-small" data-staff-reset="${s.user_id}">Nowe hasło</button>${!own?`<button class="button button-small ${s.active?'button-danger':''}" data-staff-toggle="${s.user_id}">${s.active?'Zablokuj':'Odblokuj'}</button>`:''}</div></article>`}).join('')||'<p>Brak pracowników.</p>'}
function renderProfile(){const mine=orders.filter(o=>o.accepted_by===session.user.id),issued=mine.filter(o=>o.status==='Wydane'),value=issued.reduce((a,o)=>a+Number(o.final_amount||0),0);$('profileAvatar').textContent=initials(profile.display_name);$('profileName').textContent=profile.display_name;$('profileRole').textContent=roleName(profile.role);$('profileLogin').textContent='@'+(profile.username||'—');$('profileSince').textContent=dateOnly(profile.created_at);$('profileStats').innerHTML=[['Przyjęte',mine.length],['Wydane',issued.length],['Wartość',money(value)],['Średnia',money(issued.length?value/issued.length:0)]].map(x=>`<article class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('')}
function periodOrders(){const f=$('statsFrom').value,t=$('statsTo').value;return orders.filter(o=>(!f||String(o.created_at).slice(0,10)>=f)&&(!t||String(o.created_at).slice(0,10)<=t))}
function renderPeriodStats(){if(profile?.role!=='admin')return;const os=periodOrders(),issued=os.filter(o=>o.status==='Wydane'),rev=issued.reduce((a,o)=>a+Number(o.final_amount||0),0);$('periodCards').innerHTML=[['Zlecenia',os.length],['Wydane',issued.length],['Obrót',money(rev)],['Średnia',money(issued.length?rev/issued.length:0)]].map(x=>`<article class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');const em={};os.forEach(o=>{const n=o.accepted_by_profile?.display_name||'Nieznany';em[n]??={count:0,issued:0,value:0};em[n].count++;if(o.status==='Wydane'){em[n].issued++;em[n].value+=Number(o.final_amount||0)}});$('periodEmployeeStats').innerHTML=Object.entries(em).sort((a,b)=>b[1].value-a[1].value).map(([n,v])=>`<div class="employee-row"><strong>${esc(n)}</strong><span>${v.count} / ${v.issued}</span><span class="amount">${money(v.value)}</span></div>`).join('')||'<p>Brak danych.</p>';const brands={};os.forEach(o=>{const k=`${o.device_brand} · ${o.repair_category||'Inne'}`;brands[k]=(brands[k]||0)+1});$('brandStats').innerHTML=Object.entries(brands).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([n,v])=>`<div class="employee-row"><strong>${esc(n)}</strong><span></span><span>${v}</span></div>`).join('')||'<p>Brak danych.</p>'}
const SMART_GROUPS=[
{category:'Ładowanie',words:['nie laduje','ładow','ladow','kabel','gniazdo','port','usb','lightning','magsafe']},
{category:'Bateria',words:['bateria','rozladow','rozład','trzyma','procent','kondycja','wylacza','wyłącza','puchnie']},
{category:'Wyświetlacz',words:['ekran','wyswietl','wyświetl','dotyk','szybka','pęk','pek','czarny ekran','linie','plamy']},
{category:'Aparat',words:['aparat','kamera','zdjec','zdję','ostrosc','ostrość','flash','lampa']},
{category:'Tylna klapka',words:['plecki','tylna','klapka','obudowa','szklo tyl','szkło tyl']},
{category:'Płyta główna',words:['plyta','płyta','zalany','zalanie','nie wlacza','nie włącza','restart','bootloop','zwarcie']},
{category:'Oprogramowanie',words:['system','aktualizacja','haslo','hasło','blokada','reset','oprogramowanie','dane']},
{category:'Diagnostyka',words:['diagnoza','diagnostyka','nie wiadomo','sprawdzenie']}
];
function norm(v=''){return String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function smartTokens(v){return [...new Set(norm(v).split(' ').filter(x=>x.length>2))]}
function smartHistory(brand,model,desc){const b=norm(brand),m=norm(model),tokens=smartTokens(desc),map={};orders.filter(o=>norm(o.device_brand)===b&&(!m||norm(o.device_model).includes(m)||m.includes(norm(o.device_model)))).forEach(o=>{let score=0;const text=norm(`${o.fault_description||''} ${o.repair_category||''}`);tokens.forEach(t=>{if(text.includes(t))score++});if(score||!tokens.length){const c=o.repair_category||'Inne';map[c]??={count:0,total:0,times:0};map[c].count++;const val=Number(o.final_amount||o.estimated_amount||0);if(val){map[c].total+=val;map[c].times++}}});return map}
function smartSuggestions(){const brand=$('deviceBrand').value.trim(),model=$('deviceModel').value.trim(),desc=$('faultDescription').value.trim(),query=norm(`${brand} ${model} ${desc}`),tokens=smartTokens(desc),history=smartHistory(brand,model,desc),scored=[];items.filter(i=>i.is_visible!==false).forEach(i=>{let score=0;const ib=norm(i.brand),im=norm(i.model),text=norm(`${i.category||''} ${i.service||''} ${i.description||''}`);if(brand&&ib===norm(brand))score+=8;else if(brand&&(ib.includes(norm(brand))||norm(brand).includes(ib)))score+=4;if(model&&im===norm(model))score+=12;else if(model&&(im.includes(norm(model))||norm(model).includes(im)))score+=7;tokens.forEach(t=>{if(text.includes(t))score+=3});SMART_GROUPS.forEach(g=>{if(g.words.some(w=>query.includes(norm(w)))&&norm(i.category||'')===norm(g.category))score+=9});score+=(history[i.category||'Inne']?.count||0)*1.5;if(score>2)scored.push({item:i,score,history:history[i.category||'Inne']||null})});return scored.sort((a,b)=>b.score-a.score||Number(a.item.price)-Number(b.item.price)).slice(0,6)}
function renderSmartAssist(){const box=$('smartAssistResults'),hint=$('smartAssistHint'),brand=$('deviceBrand').value.trim(),model=$('deviceModel').value.trim(),desc=$('faultDescription').value.trim();box.innerHTML='';if(!brand||!model||desc.length<3){hint.textContent='Uzupełnij markę, model i krótki opis usterki.';hint.classList.remove('hidden');return}const results=smartSuggestions();hint.classList.toggle('hidden',results.length>0);if(!results.length){hint.textContent='Brak pasujących pozycji w cenniku. Dodaj odpowiednią usługę do cennika lub wybierz diagnostykę.';return}box.innerHTML=results.map(({item,history},idx)=>`<article class="smart-card"><div><span class="smart-rank">${idx+1}</span><strong>${esc(item.service)}</strong><small>${esc(item.category||'Inne')} · ${esc(item.brand)} ${esc(item.model)}</small>${history?`<em>${history.count} podobnych zleceń${history.times?` · średnio ${money(history.total/history.times)}`:''}</em>`:''}</div><div class="smart-price">${esc(priceText(item))}<button type="button" class="button button-small" data-smart-add="${item.id}">Dodaj do wyceny</button></div></article>`).join('')}
function renderSmartSelected(){const total=smartChosen.reduce((a,x)=>a+Number(x.price||0),0);$('estimatedAmount').value=total||'';if(!smartChosen.length){$('smartSelected').classList.add('hidden');$('smartSelected').innerHTML='';return}$('smartSelected').classList.remove('hidden');$('smartSelected').innerHTML=`<strong>Wybrana wycena: ${money(total)}</strong><div>${smartChosen.map(x=>`<span>${esc(x.service)} <button type="button" data-smart-remove="${x.id}" aria-label="Usuń">×</button></span>`).join('')}</div>`}
function addSmartItem(id){const item=items.find(i=>String(i.id)===String(id));if(!item||smartChosen.some(x=>String(x.id)===String(id)))return;smartChosen.push(item);$('repairCategory').value=item.category||'Inne';renderSmartSelected()}
function removeSmartItem(id){smartChosen=smartChosen.filter(x=>String(x.id)!==String(id));renderSmartSelected()}
function renderPhotoPreview(){const box=$('selectedPhotoPreview'),files=[...$('orderPhotos').files];box.innerHTML='';files.slice(0,10).forEach(f=>{const img=document.createElement('img');img.alt=f.name;img.src=URL.createObjectURL(f);img.onload=()=>URL.revokeObjectURL(img.src);box.appendChild(img)})}
function switchDialog(dialog){if($('adminDialog').open)$('adminDialog').close();dialog.addEventListener('close',()=>{if(session&&!$('adminDialog').open)$('adminDialog').showModal()},{once:true});dialog.showModal()}
function openItem(i=null){switchDialog($('editDialog'));$('itemForm').reset();$('itemId').value=i?.id||'';$('itemFormTitle').textContent=i?'Edytuj pozycję':'Dodaj pozycję';$('itemBrand').value=i?.brand||'';$('itemModel').value=i?.model||'';$('itemCategory').value=i?.category||'Inne';$('itemService').value=i?.service||'';$('itemPrice').value=i?.price??'';$('itemPricePrefix').value=i?.price_prefix??'od';$('itemDescription').value=i?.description||'';$('itemVisible').checked=i?.is_visible!==false;$('itemError').textContent=''}
function resetSignature(data=''){const c=$('signatureCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);if(data){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,c.width,c.height);im.src=data}signatureDirty=false}
function openOrder(o=null){currentOrder=o;printAfterSave=false;smartChosen=[];switchDialog($('orderDialog'));$('orderForm').reset();$('smartAssistResults').innerHTML='';$('smartSelected').innerHTML='';$('smartSelected').classList.add('hidden');$('selectedPhotoPreview').innerHTML='';$('smartAssistHint').textContent='Wpisz markę, model i opis usterki.';$('smartAssistHint').classList.remove('hidden');$('orderId').value=o?.id||'';$('orderFormTitle').textContent=o?`Edytuj ${o.order_number}`:'Nowe zlecenie';[['customerName','customer_name'],['customerPhone','customer_phone'],['customerEmail','customer_email'],['deviceBrand','device_brand'],['deviceModel','device_model'],['deviceImei','imei'],['devicePasscode','device_passcode'],['accessories','accessories'],['deviceCondition','device_condition'],['faultDescription','fault_description'],['estimatedAmount','estimated_amount'],['depositAmount','deposit_amount'],['finalAmount','final_amount'],['dueDate','due_date'],['internalNotes','internal_notes']].forEach(([id,k])=>$(id).value=o?.[k]??'');$('orderStatus').value=o?.status||'Przyjęte';$('orderPriority').value=o?.priority||'Standard';$('repairCategory').value=o?.repair_category||'Inne';$('paymentMethod').value=o?.payment_method||'';$('customerConsent').checked=Boolean(o?.customer_consent);$('orderError').textContent='';resetSignature(o?.signature_data||'');renderExistingPhotos(o)}
async function renderExistingPhotos(o){const box=$('existingPhotos');box.innerHTML='';for(const path of o?.photo_paths||[]){const {data}=await db.storage.from('order-photos').createSignedUrl(path,3600);if(data?.signedUrl)box.innerHTML+=`<img src="${data.signedUrl}" alt="Zdjęcie urządzenia">`}}
async function uploadPhotos(orderId,files){const paths=[];for(const file of files){const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`${orderId}/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('order-photos').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;paths.push(path)}return paths}
function orderPayload(){return{customer_name:$('customerName').value.trim(),customer_phone:$('customerPhone').value.trim(),customer_email:$('customerEmail').value.trim(),device_brand:$('deviceBrand').value.trim(),device_model:$('deviceModel').value.trim(),imei:$('deviceImei').value.trim(),device_passcode:$('devicePasscode').value.trim(),accessories:$('accessories').value.trim(),device_condition:$('deviceCondition').value.trim(),fault_description:$('faultDescription').value.trim(),estimated_amount:$('estimatedAmount').value||null,deposit_amount:$('depositAmount').value||0,final_amount:$('finalAmount').value||null,due_date:$('dueDate').value||null,internal_notes:$('internalNotes').value.trim(),status:$('orderStatus').value,priority:$('orderPriority').value,repair_category:$('repairCategory').value,payment_method:$('paymentMethod').value,customer_consent:$('customerConsent').checked,signature_data:signatureDirty?$('signatureCanvas').toDataURL('image/png'):(currentOrder?.signature_data||null),updated_by:session.user.id}}
async function saveOrder(ev){ev?.preventDefault();$('orderError').textContent='';try{const payload=orderPayload();let saved;if($('orderId').value){const {data,error}=await db.from('service_orders').update(payload).eq('id',$('orderId').value).select().single();if(error)throw error;saved=data}else{payload.accepted_by=session.user.id;const {data,error}=await db.from('service_orders').insert(payload).select().single();if(error)throw error;saved=data}const files=[...$('orderPhotos').files];if(files.length){const newPaths=await uploadPhotos(saved.id,files),all=[...(saved.photo_paths||[]),...newPaths];const {data,error}=await db.from('service_orders').update({photo_paths:all,updated_by:session.user.id}).eq('id',saved.id).select().single();if(error)throw error;saved=data}$('orderDialog').close();await loadOrders();renderOrders();renderDashboard();renderPeriodStats();toast('Zlecenie zapisane.');if(printAfterSave)printOrder(saved)}catch(e){$('orderError').textContent=e.message||String(e)}}
function printOrder(o){const w=window.open('','_blank');const due=o.due_date?dateOnly(o.due_date):'—';w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(o.order_number)}</title><style>body{font-family:Arial;color:#111;padding:25px}h1{margin:0}.head{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:15px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.box{border:1px solid #aaa;padding:12px;border-radius:8px}.sign{height:90px;border-bottom:1px solid #111;margin-top:30px}.small{font-size:12px;color:#555}@media print{button{display:none}}</style></head><body><div class="head"><div><h1>Serwis Telefabryka</h1><p>Potwierdzenie przyjęcia urządzenia</p></div><strong>${esc(o.order_number)}</strong></div><div class="grid"><div class="box"><b>Klient</b><br>${esc(o.customer_name)}<br>${esc(o.customer_phone)}<br>${esc(o.customer_email||'')}</div><div class="box"><b>Urządzenie</b><br>${esc(o.device_brand)} ${esc(o.device_model)}<br>IMEI/SN: ${esc(o.imei||'—')}<br>Akcesoria: ${esc(o.accessories||'—')}</div></div><div class="box"><b>Opis usterki</b><p>${esc(o.fault_description)}</p><b>Stan urządzenia</b><p>${esc(o.device_condition||'—')}</p></div><div class="grid"><div class="box">Kwota orientacyjna: <b>${money(o.estimated_amount)}</b><br>Zaliczka: <b>${money(o.deposit_amount)}</b></div><div class="box">Status: <b>${esc(o.status)}</b><br>Termin: <b>${due}</b></div></div><p class="small">Klient potwierdza przekazanie urządzenia w opisanym stanie i zgodę na przetwarzanie danych niezbędnych do realizacji usługi. Cena orientacyjna może ulec zmianie po diagnostyce.</p><div class="grid"><div><div class="sign"></div><p>Podpis klienta</p></div><div><div class="sign"></div><p>Podpis serwisu</p></div></div><button onclick="print()">Drukuj</button></body></html>`);w.document.close();setTimeout(()=>w.print(),300)}
function openStaff(s=null){switchDialog($('staffDialog'));$('staffForm').reset();$('staffUserId').value=s?.user_id||'';$('staffFormTitle').textContent=s?'Edytuj pracownika':'Dodaj pracownika';$('staffDisplayName').value=s?.display_name||'';$('staffUsername').value=s?.username||'';$('staffUsername').disabled=Boolean(s);$('staffPassword').required=!s;$('staffPassword').value='';$('staffPasswordLabel').classList.toggle('hidden',Boolean(s));$('staffRole').value=s?.role||'employee';$('staffActive').checked=s?.active!==false;$('staffError').textContent=''}
async function staffAction(body){const {data,error}=await db.functions.invoke('staff-admin',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
async function saveStaff(ev){ev.preventDefault();$('staffError').textContent='';try{const id=$('staffUserId').value;if(id)await staffAction({action:'update',user_id:id,display_name:$('staffDisplayName').value.trim(),role:$('staffRole').value,active:$('staffActive').checked});else await staffAction({action:'create',display_name:$('staffDisplayName').value.trim(),username:$('staffUsername').value.trim(),password:$('staffPassword').value,role:$('staffRole').value});$('staffDialog').close();await loadStaff();renderStaff();toast('Konto zapisane.')}catch(e){$('staffError').textContent=e.message||String(e)}}
async function history(id){const o=orders.find(x=>x.id===id),{data,error}=await db.from('order_history').select('*, staff_profiles(display_name)').eq('order_id',id).order('created_at',{ascending:false});if(error)return toast(error.message,'error');$('historyTitle').textContent=o?.order_number||'Historia';$('historyList').innerHTML=(data||[]).map(h=>`<div class="history-item"><strong>${esc(h.action)}</strong><p>${esc(h.staff_profiles?.display_name||'System')} · ${fmt(h.created_at)}</p></div>`).join('')||'<p>Brak historii.</p>';switchDialog($('historyDialog'))}
function setTab(name){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${name}`));$('workspaceTitle').textContent=({dashboard:'Dashboard',orders:'Zlecenia',prices:'Cennik',staff:'Pracownicy',stats:'Statystyki',profile:'Mój profil'})[name]||name}

async function loadCatalog(){const [m,t]=await Promise.all([db.from('device_models').select('*').order('brand').order('model'),db.from('service_templates').select('*').order('category').order('service')]);if(m.error)return toast(m.error.message,'error');if(t.error)return toast(t.error.message,'error');deviceModels=m.data||[];serviceTemplates=t.data||[];renderCatalog()}
function renderCatalog(){if(!$('catalogSummary'))return;const activeModels=deviceModels.filter(x=>x.active!==false),activeTemplates=serviceTemplates.filter(x=>x.active!==false),hidden=items.filter(x=>!x.is_visible).length;$('catalogSummary').innerHTML=[['Modele',activeModels.length,'W bazie katalogu'],['Szablony',activeTemplates.length,'Automatyczne usługi'],['Pozycje cennika',items.length,'Łącznie'],['Do uzupełnienia',hidden,'Ukryte / bez publikacji']].map(x=>`<article class="stat-card"><span>${esc(x[0])}</span><strong>${x[1]}</strong><small>${esc(x[2])}</small></article>`).join('');$('templateCards').innerHTML=serviceTemplates.map(t=>`<article class="catalog-card"><div><strong>${esc(t.service)}</strong><small>${esc(t.category)} · ${(t.brands||[]).map(esc).join(', ')||'Wszystkie marki'}</small></div><span class="pill">${t.active?'Aktywny':'Wyłączony'}</span></article>`).join('')||'<p class="muted">Brak szablonów.</p>';renderModels()}
function renderModels(){if(!$('modelCards'))return;const q=($('modelSearch')?.value||'').trim().toLowerCase(),list=deviceModels.filter(m=>!q||`${m.brand} ${m.model}`.toLowerCase().includes(q));$('modelCards').innerHTML=list.slice(0,350).map(m=>`<article class="catalog-card"><div><strong>${esc(m.brand)}</strong><small>${esc(m.model)}</small></div><span class="pill">${m.active?'Aktywny':'Wyłączony'}</span></article>`).join('')||'<p class="muted">Brak modeli.</p>'}
async function syncCatalog(){const b=$('syncCatalogButton');if(b){b.disabled=true;b.textContent='Synchronizuję…'}const {data,error}=await db.rpc('sync_price_catalog');if(b){b.disabled=false;b.textContent='↻ Synchronizuj cennik'}if(error)return toast(error.message,'error');await Promise.all([loadItems(),loadCatalog()]);renderAdminPrices();toast(`Synchronizacja zakończona${data!=null?`: dodano ${data} pozycji`:''}.`)}
function openModelDialog(){$('modelForm').reset();$('catalogModelActive').checked=true;$('modelFormError').textContent='';switchDialog($('modelDialog'))}
function openTemplateDialog(){$('templateForm').reset();$('templateActive').checked=true;$('templateBrands').value='Apple, Samsung';$('templateFormError').textContent='';switchDialog($('templateDialog'))}
async function saveModel(e){e.preventDefault();$('modelFormError').textContent='';const payload={brand:$('catalogModelBrand').value.trim(),model:$('catalogModelName').value.trim(),active:$('catalogModelActive').checked},{error}=await db.from('device_models').insert(payload);if(error)return $('modelFormError').textContent=error.message;$('modelDialog').close();await syncCatalog()}
async function saveTemplate(e){e.preventDefault();$('templateFormError').textContent='';const brands=$('templateBrands').value.split(',').map(x=>x.trim()).filter(Boolean),payload={service:$('templateService').value.trim(),category:$('templateCategory').value,brands,description:$('templateDescription').value.trim(),active:$('templateActive').checked},{error}=await db.from('service_templates').insert(payload);if(error)return $('templateFormError').textContent=error.message;$('templateDialog').close();await syncCatalog()}
async function init(){if(!configured){toast('Brak konfiguracji Supabase w config.js','error');return}$('orderStatus').innerHTML=STATUSES.map(s=>`<option>${s}</option>`).join('');$('orderStatusFilter').innerHTML='<option value="">Wszystkie statusy</option>'+STATUSES.map(s=>`<option>${s}</option>`).join('');const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1);$('statsFrom').value=first.toISOString().slice(0,10);$('statsTo').value=now.toISOString().slice(0,10);await Promise.all([loadItems(),refreshAuth()]);
$('adminButton').onclick=openPanel;$('statusLookupButton').onclick=()=>$('statusDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('searchInput').oninput=renderPrices;$('brandFilter').onchange=renderPrices;$('categoryFilter').onchange=renderPrices;$('brandStrip').onclick=e=>{const b=e.target.closest('[data-brand-chip]');if(b){$('brandFilter').value=b.dataset.brandChip;renderPrices()}};$('exportPriceButton').onclick=()=>window.print();$('printPriceAdminButton').onclick=()=>window.print();$('exportPriceAdminButton').onclick=()=>download('telefabryka-cennik.csv',csv([['Marka','Model','Kategoria','Usługa','Cena','Prefiks'],...items.map(i=>[i.brand,i.model,i.category,i.service,i.price,i.price_prefix])]));
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';let login=$('loginEmail').value.trim().toLowerCase();if(!login.includes('@'))login+= '@telefabryka.local';const {error}=await db.auth.signInWithPassword({email:login,password:$('loginPassword').value});if(error)return $('loginError').textContent='Nieprawidłowy login lub hasło.';$('loginDialog').close();await refreshAuth();await openPanel()};$('logoutButton').onclick=async()=>{await db.auth.signOut();$('adminDialog').close();await refreshAuth()};document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('newOrderButton').onclick=()=>openOrder();$('newItemButton').onclick=()=>openItem();$('newStaffButton').onclick=()=>openStaff();$('newModelButton').onclick=openModelDialog;$('newTemplateButton').onclick=openTemplateDialog;$('syncCatalogButton').onclick=syncCatalog;$('modelSearch').oninput=renderModels;$('modelForm').onsubmit=saveModel;$('templateForm').onsubmit=saveTemplate;$('itemForm').onsubmit=async e=>{e.preventDefault();const p={brand:$('itemBrand').value.trim(),model:$('itemModel').value.trim(),category:$('itemCategory').value,service:$('itemService').value.trim(),price:$('itemPrice').value,price_prefix:$('itemPricePrefix').value,description:$('itemDescription').value.trim(),is_visible:$('itemVisible').checked},id=$('itemId').value,{error}=id?await db.from('price_items').update(p).eq('id',id):await db.from('price_items').insert(p);if(error)return $('itemError').textContent=error.message;$('editDialog').close();await loadItems();renderAdminPrices()};
$('adminRows').onclick=async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete,toggle=e.target.dataset.toggleVisible;if(edit)openItem(items.find(i=>i.id===edit));if(toggle){const item=items.find(i=>i.id===toggle);if(!item)return;const next=!item.is_visible;e.target.disabled=true;const {error}=await db.from('price_items').update({is_visible:next}).eq('id',toggle);if(error){e.target.disabled=false;return toast(error.message,'error')}item.is_visible=next;renderAdminPrices();renderPrices();toast(next?'Pozycja aktywna.':'Pozycja ukryta.')}if(del&&confirm('Usunąć pozycję?')){const {error}=await db.from('price_items').delete().eq('id',del);if(error)toast(error.message,'error');else{await loadItems();renderAdminPrices()}}};$('tab-prices').onclick=e=>{const d=e.target.dataset.pricePage;if(d==='prev'&&adminPricePage>1){adminPricePage--;renderAdminPrices()}if(d==='next'){adminPricePage++;renderAdminPrices()}};$('orderForm').onsubmit=saveOrder;$('savePrintOrder').onclick=async()=>{printAfterSave=true;$('orderForm').requestSubmit()};$('orderRows').onclick=async e=>{const id=e.target.dataset.orderEdit||e.target.dataset.print||e.target.dataset.history||e.target.dataset.orderDelete;if(!id)return;const o=orders.find(x=>x.id===id);if(e.target.dataset.orderEdit)openOrder(o);if(e.target.dataset.print)printOrder(o);if(e.target.dataset.history)history(id);if(e.target.dataset.orderDelete&&confirm(`Usunąć ${o.order_number}?`)){const {error}=await db.from('service_orders').delete().eq('id',id);if(error)toast(error.message,'error');else{await loadOrders();renderOrders();renderDashboard()}}};$('orderRows').onchange=async e=>{const id=e.target.dataset.statusId;if(!id)return;const {error}=await db.from('service_orders').update({status:e.target.value,updated_by:session.user.id}).eq('id',id);if(error)toast(error.message,'error');await loadOrders();renderOrders();renderDashboard()};$('orderSearch').oninput=renderOrders;$('orderStatusFilter').onchange=renderOrders;$('orderPriorityFilter').onchange=renderOrders;$('exportOrdersButton').onclick=()=>download('telefabryka-zlecenia.csv',csv([['Numer','Data','Klient','Telefon','Urządzenie','IMEI','Status','Priorytet','Kwota','Przyjął'],...filteredOrders().map(o=>[o.order_number,o.created_at,o.customer_name,o.customer_phone,`${o.device_brand} ${o.device_model}`,o.imei,o.status,o.priority,o.final_amount||o.estimated_amount,o.accepted_by_profile?.display_name])]));
$('staffForm').onsubmit=saveStaff;$('staffSearch').oninput=renderStaff;$('staffCards').onclick=async e=>{const edit=e.target.dataset.staffEdit,reset=e.target.dataset.staffReset,toggle=e.target.dataset.staffToggle;if(edit)openStaff(staff.find(s=>s.user_id===edit));if(reset){const pass=prompt('Wpisz nowe hasło (minimum 8 znaków):');if(pass)try{await staffAction({action:'reset_password',user_id:reset,password:pass});toast('Hasło zmienione.')}catch(x){toast(x.message,'error')}}if(toggle){const s=staff.find(x=>x.user_id===toggle);try{await staffAction({action:'update',user_id:toggle,display_name:s.display_name,role:s.role,active:!s.active});await loadStaff();renderStaff()}catch(x){toast(x.message,'error')}}};$('refreshStatsButton').onclick=renderPeriodStats;$('statsFrom').onchange=renderPeriodStats;$('statsTo').onchange=renderPeriodStats;$('exportStatsButton').onclick=()=>{const os=periodOrders();download('telefabryka-statystyki.csv',csv([['Pracownik','Liczba','Wydane','Wartość'],...staff.map(s=>{const x=os.filter(o=>o.accepted_by===s.user_id),w=x.filter(o=>o.status==='Wydane');return[s.display_name,x.length,w.length,w.reduce((a,o)=>a+Number(o.final_amount||0),0)]})]))};
$('statusForm').onsubmit=async e=>{e.preventDefault();$('lookupError').textContent='';$('lookupResult').classList.add('hidden');const {data,error}=await db.rpc('public_order_status',{p_order_number:$('lookupNumber').value.trim().toUpperCase(),p_phone:$('lookupPhone').value.trim()});if(error||!data?.length)return $('lookupError').textContent='Nie znaleziono zlecenia. Sprawdź numer i telefon.';const o=data[0];$('lookupResult').innerHTML=`<span class="eyebrow">${esc(o.order_number)}</span><h3>${esc(o.device_brand)} ${esc(o.device_model)}</h3><strong>${esc(o.status)}</strong><p>Przyjęto: ${dateOnly(o.created_at)}${o.due_date?` · termin: ${dateOnly(o.due_date)}`:''}</p>`;$('lookupResult').classList.remove('hidden')};
$('runSmartAssist').onclick=renderSmartAssist;$('smartAssistResults').onclick=e=>{const id=e.target.dataset.smartAdd;if(id)addSmartItem(id)};$('smartSelected').onclick=e=>{const id=e.target.dataset.smartRemove;if(id)removeSmartItem(id)};$('orderPhotos').onchange=renderPhotoPreview;let smartTimer;['deviceBrand','deviceModel','faultDescription'].forEach(id=>$(id).addEventListener('input',()=>{clearTimeout(smartTimer);smartTimer=setTimeout(()=>{if($('faultDescription').value.trim().length>7)renderSmartAssist()},450)}));
const canvas=$('signatureCanvas'),ctx=canvas.getContext('2d');let drawing=false,last=null;function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}function start(e){drawing=true;last=pos(e);e.preventDefault()}function move(e){if(!drawing)return;const p=pos(e);ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;signatureDirty=true;e.preventDefault()}function end(){drawing=false}canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);$('clearSignature').onclick=()=>resetSignature();
db.auth.onAuthStateChange(()=>refreshAuth())}
document.addEventListener('DOMContentLoaded',init);
})();