(() => {
'use strict';
const cfg=window.TELEFABRYKA_CONFIG||{};const configured=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY);const db=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;const $=id=>document.getElementById(id);
const STATUSES=['Przyjęte','Diagnoza','Oczekiwanie na część','W naprawie','Gotowe','Wydane','Anulowane'];
const els={list:$('priceList'),empty:$('emptyState'),search:$('searchInput'),brand:$('brandFilter'),category:$('categoryFilter'),brandStrip:$('brandStrip'),status:$('statusBanner'),adminButton:$('adminButton'),loginDialog:$('loginDialog'),loginForm:$('loginForm'),loginEmail:$('loginEmail'),loginPassword:$('loginPassword'),loginError:$('loginError'),adminDialog:$('adminDialog'),adminRows:$('adminRows'),adminEmail:$('adminEmail'),adminName:$('adminName'),logout:$('logoutButton'),newItem:$('newItemButton'),editDialog:$('editDialog'),itemForm:$('itemForm'),itemFormTitle:$('itemFormTitle'),itemId:$('itemId'),itemBrand:$('itemBrand'),itemModel:$('itemModel'),itemCategory:$('itemCategory'),itemService:$('itemService'),itemPrice:$('itemPrice'),itemPricePrefix:$('itemPricePrefix'),itemDescription:$('itemDescription'),itemVisible:$('itemVisible'),itemError:$('itemError'),template:$('cardTemplate'),newOrder:$('newOrderButton'),orderDialog:$('orderDialog'),orderForm:$('orderForm'),orderRows:$('orderRows'),orderSearch:$('orderSearch'),orderStatusFilter:$('orderStatusFilter'),orderStatus:$('orderStatus'),orderError:$('orderError'),historyDialog:$('historyDialog'),historyTitle:$('historyTitle'),historyList:$('historyList'),statsCards:$('statsCards'),statusStats:$('statusStats'),employeeStats:$('employeeStats')};
let items=[],orders=[],session=null,profile=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=v=>Number(v||0).toLocaleString('pl-PL',{minimumFractionDigits:0,maximumFractionDigits:2})+' zł';const priceText=i=>`${i.price_prefix?i.price_prefix+' ':''}${money(i.price)}`;const fmt=d=>d?new Date(d).toLocaleString('pl-PL'):'—';const initials=b=>(b||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
function showStatus(t,type='warn'){els.status.textContent=t;els.status.className=`status ${type==='error'?'error':''}`}function hideStatus(){els.status.className='status hidden'}
async function loadItems(){const {data,error}=await db.from('price_items').select('*').order('brand').order('model');if(error){showStatus(error.message,'error');return}items=data||[];hideStatus();renderPrices()}
function renderPrices(){const q=els.search.value.trim().toLowerCase(),b=els.brand.value,c=els.category.value;const visible=items.filter(i=>i.is_visible!==false);const brands=[...new Set(visible.map(i=>i.brand))].sort((a,b)=>a.localeCompare(b,'pl'));const cats=[...new Set(visible.map(i=>i.category||'Inne'))].sort((a,b)=>a.localeCompare(b,'pl'));const oldB=els.brand.value,oldC=els.category.value;els.brand.innerHTML='<option value="">Wszystkie marki</option>'+brands.map(x=>`<option>${esc(x)}</option>`).join('');els.category.innerHTML='<option value="">Wszystkie kategorie</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('');if(brands.includes(oldB))els.brand.value=oldB;if(cats.includes(oldC))els.category.value=oldC;els.brandStrip.innerHTML=brands.map(x=>`<button class="brand-chip" data-brand-chip="${esc(x)}">${esc(x)}</button>`).join('');const filtered=visible.filter(i=>(!b||i.brand===b)&&(!c||(i.category||'Inne')===c)&&(!q||`${i.brand} ${i.model} ${i.category||''} ${i.service} ${i.description||''}`.toLowerCase().includes(q)));els.list.innerHTML='';filtered.forEach(i=>{const n=els.template.content.cloneNode(true);n.querySelector('.brand-mark').textContent=initials(i.brand);n.querySelector('.tag').textContent=i.category||i.brand;n.querySelector('h2').textContent=`${i.brand} ${i.model}`;n.querySelector('.service').textContent=i.service;n.querySelector('.description').textContent=i.description||'Cena orientacyjna';n.querySelector('.price').textContent=priceText(i);els.list.appendChild(n)});els.empty.classList.toggle('hidden',filtered.length>0)}
async function refreshAuth(){const {data}=await db.auth.getSession();session=data.session;if(session){const {data:p}=await db.from('staff_profiles').select('*').eq('user_id',session.user.id).maybeSingle();profile=p||{display_name:session.user.email,role:'employee',active:true}}els.adminButton.textContent=session?'Otwórz panel':'Panel pracownika'}
async function openPanel(){await refreshAuth();if(!session){els.loginError.textContent='';els.loginDialog.showModal();return}await loadPanel();els.adminDialog.showModal()}
async function loadPanel(){els.adminEmail.textContent=session.user.email;els.adminName.textContent=profile?.display_name||'';document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden-role',profile?.role!=='admin'));await Promise.all([loadItems(),loadOrders()]);renderAdminPrices();renderOrders();renderStats()}
async function loadOrders(){const {data,error}=await db.from('service_orders').select('*, accepted_by_profile:staff_profiles!service_orders_accepted_by_fkey(display_name)').order('created_at',{ascending:false});if(error){alert('Błąd zleceń: '+error.message);orders=[]}else orders=data||[]}
function renderAdminPrices(){els.adminRows.innerHTML=items.map(i=>`<tr><td><strong>${esc(i.brand)}</strong><small>${esc(i.model)}</small></td><td>${esc(i.category||'Inne')}<small>${esc(i.service)}</small></td><td>${esc(priceText(i))}</td><td><span class="pill ${i.is_visible?'on':'off'}">${i.is_visible?'Widoczna':'Ukryta'}</span></td><td><div class="row-actions">${profile?.role==='admin'?`<button class="button button-ghost" data-edit="${i.id}">Edytuj</button><button class="button button-danger" data-delete="${i.id}">Usuń</button>`:'—'}</div></td></tr>`).join('')}
function renderOrders(){const q=els.orderSearch.value.trim().toLowerCase(),s=els.orderStatusFilter.value;const filtered=orders.filter(o=>(!s||o.status===s)&&(!q||`${o.order_number} ${o.customer_name} ${o.customer_phone} ${o.device_brand} ${o.device_model} ${o.imei||''}`.toLowerCase().includes(q)));els.orderRows.innerHTML=filtered.map(o=>`<tr><td><strong>${esc(o.order_number)}</strong><small>${fmt(o.created_at)}</small></td><td>${esc(o.customer_name)}<small>${esc(o.customer_phone)}</small></td><td>${esc(o.device_brand)} ${esc(o.device_model)}<small>${esc(o.fault_description)}</small></td><td><select class="status-select" data-status-id="${o.id}">${STATUSES.map(x=>`<option ${x===o.status?'selected':''}>${x}</option>`).join('')}</select></td><td class="amount">${money(o.final_amount||o.estimated_amount)}</td><td>${esc(o.accepted_by_profile?.display_name||'—')}</td><td><div class="row-actions"><button class="button button-ghost" data-order-edit="${o.id}">Edytuj</button><button class="button button-ghost" data-history="${o.id}">Historia</button></div></td></tr>`).join('')}
function renderStats(){const active=orders.filter(o=>o.status!=='Anulowane');const today=new Date().toISOString().slice(0,10);const todayOrders=active.filter(o=>String(o.created_at).slice(0,10)===today);const issued=active.filter(o=>o.status==='Wydane');const revenue=issued.reduce((a,o)=>a+Number(o.final_amount||0),0);const cards=[['Przyjęte dziś',todayOrders.length],['W naprawie',active.filter(o=>o.status==='W naprawie').length],['Gotowe',active.filter(o=>o.status==='Gotowe').length],['Obrót wydanych',money(revenue)]];els.statsCards.innerHTML=cards.map(x=>`<article class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');const max=Math.max(1,...STATUSES.map(s=>orders.filter(o=>o.status===s).length));els.statusStats.innerHTML=STATUSES.map(s=>{const n=orders.filter(o=>o.status===s).length;return `<div class="progress-row"><span>${s}</span><div class="progress"><i style="width:${n/max*100}%"></i></div><strong>${n}</strong></div>`}).join('');const map={};orders.forEach(o=>{const name=o.accepted_by_profile?.display_name||'Nieznany';map[name]??={count:0,value:0};map[name].count++;if(o.status==='Wydane')map[name].value+=Number(o.final_amount||0)});els.employeeStats.innerHTML=Object.entries(map).sort((a,b)=>b[1].count-a[1].count).map(([n,v])=>`<div class="employee-row"><strong>${esc(n)}</strong><span>${v.count} zleceń</span><span class="amount">${money(v.value)}</span></div>`).join('')||'<p class="description">Brak danych.</p>'}
function openItem(i=null){els.itemForm.reset();els.itemId.value=i?.id||'';els.itemFormTitle.textContent=i?'Edytuj pozycję':'Dodaj pozycję';els.itemBrand.value=i?.brand||'';els.itemModel.value=i?.model||'';els.itemCategory.value=i?.category||'Inne';els.itemService.value=i?.service||'';els.itemPrice.value=i?.price??'';els.itemPricePrefix.value=i?.price_prefix??'od';els.itemDescription.value=i?.description||'';els.itemVisible.checked=i?.is_visible!==false;els.editDialog.showModal()}
function openOrder(o=null){els.orderForm.reset();$('orderId').value=o?.id||'';$('orderFormTitle').textContent=o?'Edytuj zlecenie':'Nowe zlecenie';$('customerName').value=o?.customer_name||'';$('customerPhone').value=o?.customer_phone||'';$('deviceBrand').value=o?.device_brand||'';$('deviceModel').value=o?.device_model||'';$('deviceImei').value=o?.imei||'';$('accessories').value=o?.accessories||'';$('faultDescription').value=o?.fault_description||'';$('deviceCondition').value=o?.device_condition||'';$('estimatedAmount').value=o?.estimated_amount??'';$('finalAmount').value=o?.final_amount??'';$('orderStatus').value=o?.status||'Przyjęte';$('dueDate').value=o?.due_date||'';$('internalNotes').value=o?.internal_notes||'';els.orderError.textContent='';els.orderDialog.showModal()}
function csv(name,rows){const data=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function showHistory(id){const o=orders.find(x=>x.id===id);els.historyTitle.textContent=o?.order_number||'';const {data,error}=await db.from('order_history').select('*, changed_by_profile:staff_profiles!order_history_changed_by_fkey(display_name)').eq('order_id',id).order('created_at',{ascending:false});els.historyList.innerHTML=error?`<p>${esc(error.message)}</p>`:(data||[]).map(h=>`<div class="history-entry"><strong>${esc(h.action)}</strong><small>${esc(h.changed_by_profile?.display_name||'System')} · ${fmt(h.created_at)}</small>${h.details?`<small>${esc(JSON.stringify(h.details))}</small>`:''}</div>`).join('')||'<p>Brak historii.</p>';els.historyDialog.showModal()}
STATUSES.forEach(s=>{els.orderStatus.insertAdjacentHTML('beforeend',`<option>${s}</option>`);els.orderStatusFilter.insertAdjacentHTML('beforeend',`<option>${s}</option>`)});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active')}));
els.search.addEventListener('input',renderPrices);els.brand.addEventListener('change',renderPrices);els.category.addEventListener('change',renderPrices);els.brandStrip.addEventListener('click',e=>{const b=e.target.closest('[data-brand-chip]');if(b){els.brand.value=b.dataset.brandChip;renderPrices()}});els.adminButton.addEventListener('click',openPanel);
els.loginForm.addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:els.loginEmail.value.trim(),password:els.loginPassword.value});if(error){els.loginError.textContent=error.message;return}session=data.session;els.loginDialog.close();await refreshAuth();await loadPanel();els.adminDialog.showModal()});els.logout.addEventListener('click',async()=>{await db.auth.signOut();session=null;profile=null;els.adminDialog.close();els.adminButton.textContent='Panel pracownika'});
els.newItem.addEventListener('click',()=>openItem());els.adminRows.addEventListener('click',async e=>{const ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(ed)openItem(items.find(i=>i.id===ed.dataset.edit));if(del&&confirm('Usunąć pozycję?')){const {error}=await db.from('price_items').delete().eq('id',del.dataset.delete);if(error)alert(error.message);else{await loadItems();renderAdminPrices()}}});
els.itemForm.addEventListener('submit',async e=>{e.preventDefault();const p={brand:els.itemBrand.value.trim(),model:els.itemModel.value.trim(),category:els.itemCategory.value,service:els.itemService.value.trim(),price:Number(els.itemPrice.value),price_prefix:els.itemPricePrefix.value,description:els.itemDescription.value.trim(),is_visible:els.itemVisible.checked,updated_at:new Date().toISOString()};const r=els.itemId.value?await db.from('price_items').update(p).eq('id',els.itemId.value):await db.from('price_items').insert(p);if(r.error){els.itemError.textContent=r.error.message;return}els.editDialog.close();await loadItems();renderAdminPrices()});
els.newOrder.addEventListener('click',()=>openOrder());els.orderSearch.addEventListener('input',renderOrders);els.orderStatusFilter.addEventListener('change',renderOrders);els.orderRows.addEventListener('change',async e=>{const s=e.target.closest('[data-status-id]');if(!s)return;const {error}=await db.from('service_orders').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.statusId);if(error)alert(error.message);else{await loadOrders();renderOrders();renderStats()}});els.orderRows.addEventListener('click',e=>{const ed=e.target.closest('[data-order-edit]'),h=e.target.closest('[data-history]');if(ed)openOrder(orders.find(o=>o.id===ed.dataset.orderEdit));if(h)showHistory(h.dataset.history)});
els.orderForm.addEventListener('submit',async e=>{e.preventDefault();const id=$('orderId').value;const p={customer_name:$('customerName').value.trim(),customer_phone:$('customerPhone').value.trim(),device_brand:$('deviceBrand').value.trim(),device_model:$('deviceModel').value.trim(),imei:$('deviceImei').value.trim(),accessories:$('accessories').value.trim(),fault_description:$('faultDescription').value.trim(),device_condition:$('deviceCondition').value.trim(),estimated_amount:$('estimatedAmount').value?Number($('estimatedAmount').value):null,final_amount:$('finalAmount').value?Number($('finalAmount').value):null,status:$('orderStatus').value,due_date:$('dueDate').value||null,internal_notes:$('internalNotes').value.trim(),updated_at:new Date().toISOString()};if(!id)p.accepted_by=session.user.id;const r=id?await db.from('service_orders').update(p).eq('id',id):await db.from('service_orders').insert(p);if(r.error){els.orderError.textContent=r.error.message;return}els.orderDialog.close();await loadOrders();renderOrders();renderStats()});
$('exportPriceButton').addEventListener('click',()=>window.print());$('exportPriceAdminButton').addEventListener('click',()=>csv('cennik-telefabryka.csv',[['Marka','Model','Kategoria','Usługa','Cena','Opis'],...items.map(i=>[i.brand,i.model,i.category,i.service,priceText(i),i.description])]));$('exportOrdersButton').addEventListener('click',()=>csv('zlecenia-telefabryka.csv',[['Numer','Data','Klient','Telefon','Marka','Model','Status','Kwota','Przyjął'],...orders.map(o=>[o.order_number,fmt(o.created_at),o.customer_name,o.customer_phone,o.device_brand,o.device_model,o.status,o.final_amount||o.estimated_amount,o.accepted_by_profile?.display_name])]));
if(!configured){showStatus('Brak konfiguracji Supabase w config.js.','error')}else refreshAuth().then(loadItems);
})();