create table if not exists public.prices (
  id bigint generated by default as identity primary key,
  brand text not null,
  model text not null,
  service text not null,
  price numeric(10,2) not null check (price >= 0),
  note text default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.prices enable row level security;
alter table public.admins enable row level security;

create policy "Public can view active prices" on public.prices
for select using (active = true or auth.uid() in (select user_id from public.admins));

create policy "Admins can insert prices" on public.prices
for insert to authenticated with check (auth.uid() in (select user_id from public.admins));
create policy "Admins can update prices" on public.prices
for update to authenticated using (auth.uid() in (select user_id from public.admins)) with check (auth.uid() in (select user_id from public.admins));
create policy "Admins can delete prices" on public.prices
for delete to authenticated using (auth.uid() in (select user_id from public.admins));

create policy "Admin can verify own role" on public.admins
for select to authenticated using (user_id = auth.uid());

insert into public.prices (brand, model, service, price, note) values
('Apple','iPhone 13','Wymiana wyświetlacza',649,'część premium'),
('Apple','iPhone 13','Wymiana baterii',249,'z montażem'),
('Samsung','Galaxy S22','Wymiana złącza ładowania',299,''),
('Xiaomi','Redmi Note 12','Wymiana szybki aparatu',129,'');

-- Po utworzeniu użytkownika w Authentication > Users wstaw jego UUID:
-- insert into public.admins (user_id) values ('TU-WKLEJ-UUID-UZYTKOWNIKA');
